name: Check and Deploy
on: [push]

jobs:
  check:
    uses: ./.github/workflows/check.yml

  deploy:
    name: Deploy to Cloudflare
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn
      - name: Run wrangler publish
        run: |
          npx wrangler publish \
            --name=${{ secrets.CLOUDFLARE_WORKER_NAME }} \
            --compatibility-date=$(date -I)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
