name: Test and Deploy
on: [push, pull_request]

jobs:
  test:
    name: ESLint and UnitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test

  deploy:
    name: Deploy to Cloudflare
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn global add wrangler
      - run: yarn
      - name: Run wrangler publish
        run: |
          wrangler publish \
            --name=${{ secrets.CLOUDFLARE_WORKER_NAME }} \
            --compatibility-date=$(date -I)
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
